// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/sev/distribution": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get distribution of status codes for a time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get HTTP status code distribution",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2026-03-19 00:00:00",
                        "description": "Start Time",
                        "name": "start_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "2026-03-20 00:00:00",
                        "description": "End Time",
                        "name": "end_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Log File or Source ID (optional)",
                        "name": "log_file",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SvcWatch_internal_utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sev/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Query parsed Nginx logs with comprehensive filtering, sorting, and pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Query detailed logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size (default 50, max 500)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026-03-19 00:00:00",
                        "description": "Start Time",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2026-03-20 00:00:00",
                        "description": "End Time",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Log File or Source ID",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "192.168.1.1",
                        "description": "IP address (supports prefix match)",
                        "name": "ip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "GET",
                        "description": "HTTP Method (e.g. GET)",
                        "name": "method",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 200,
                        "description": "Exact HTTP Status (e.g. 500)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "5xx",
                        "description": "HTTP Status Class (e.g. 5xx)",
                        "name": "status_class",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "api",
                        "description": "Keyword to search in URL path",
                        "name": "path_keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 100,
                        "description": "Minimum Latency in ms",
                        "name": "min_latency",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 5000,
                        "description": "Maximum Latency in ms",
                        "name": "max_latency",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "time_desc",
                            "latency_desc"
                        ],
                        "type": "string",
                        "default": "time_desc",
                        "description": "Sort order (time_desc or latency_desc)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SvcWatch_internal_utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sev/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get overview statistics with comparison for a time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get business overview key metrics",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2026-03-19 00:00:00",
                        "description": "Start Time",
                        "name": "start_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "2026-03-20 00:00:00",
                        "description": "End Time",
                        "name": "end_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Log File or Source ID (optional)",
                        "name": "log_file",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SvcWatch_internal_utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sev/ping": {
            "get": {
                "description": "Returns pong message to check if API is alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SvcWatch_internal_utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sev/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get total logs count for all monitored tables",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get aggregated logs statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SvcWatch_internal_utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "SvcWatch_internal_utils.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SvcWatch API",
	Description:      "SvcWatch is a real-time Nginx log monitoring system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
